### ISSUE TITLE
User threads starvation

### ISSUE THREAD

**Issue by guhwanbae** [luminousmen/grokking_concurrency#1]
https://github.com/luminousmen/grokking_concurrency/blob/af926a93febcd137d7beb11ff79d2077d956c73b/Chapter%208/reader_writer/reader_writer.py#L41-L43

In Librarian::run function, Librarian thread releases a writer lock and then immediately acquires a writer lock.
Other User threads can not acquire a writer lock in RWLock::acquire_read function. so... User threads result in starvation.
I think Librarian thread should release a writer lock before sleeping. :)

**Comment by luminousmen** [comment]
You've got a point, but there's a bit more to it :) 

The reason I put `time.sleep` in the `Librarian` class was to mimic what happens in real life — like running some complex calculations, dealing with transactions, or anything else you'd expect in an actual app. It’s there to make the example feel more real, even if it ended up being a bit confusing.

I see where you're coming from with the concern about reader threads potentially getting stuck waiting. It wasn't meant to be a bug, but more like a simplification for the example that didn't quite hit the mark.

Adding another `time.sleep` after letting go of the writer lock could give the user threads some breathing room, making sure they get their turn without getting sidelined. So, you're right about the possibility of starvation — it's something to watch out for.

Either way thanks for pointing it out!
