### ISSUE TITLE
Ch#6. Arcade machine event never set True

### ISSUE THREAD

**Issue by peaceful-djony** [luminousmen/grokking_concurrency#3]
In Chapter#6 there is no code to set Event flag (`set()` method).
THere is only create `processor_free` with default flag False:
https://github.com/luminousmen/grokking_concurrency/blob/667d37e16e3ab2b4bada0f75af38b26df607290f/Chapter%206/arcade_machine.py#L11

Coeerct me if I'm wrong, but at 12th line we have to call `processor_free.set()` and immediatelly after `self.func()` set Event once again.

**Comment by luminousmen** [comment]
Hey Evgeniy, I think you're right! Thanks for pointing that out - I will update the code
